/**
 * Polygon registry — the single lookup point from a journal's JSON `polygonKey`
 * to the actual boundary vertices.
 *
 * Each journal's `exploredAreas` entries carry a `polygonKey` field that names
 * the boundary to use (e.g. "whitefield"). That key is resolved here to the
 * matching TS export. Source arrays live in their own file under this folder
 * (polygon<Area>.ts, generated by scripts/generate-isochrone.mjs) so the points
 * never get duplicated into JSON.
 *
 * All boundaries here are DRIVE-TIME ISOCHRONES (reachable zones via the Valhalla
 * routing engine), not statutory admin boundaries. They are anchored on each
 * area's pin coordinate, so every journal pin is guaranteed to lie inside its
 * own region — unlike OSM ward boundaries, which often disagree with the pins.
 */

import { whitefieldIsochronePoints } from "./polygonPointsWhitefield";
import { hennurRoadIsochronePoints } from "./polygonPointsHennurRoad";
import { hebbalAirportBeltIsochronePoints } from "./polygonPointsHebbalAirportBelt";

// the-quiet-crorepatis
import { jpNagar7thPhaseIsochronePoints } from "./polygonQuietCrorepatisJPNagar";
import { jayanagar4thBlockIsochronePoints } from "./polygonQuietCrorepatisJayanagar";
import { banashankari3rdStageIsochronePoints } from "./polygonQuietCrorepatisBanashankari";

// the-spreadsheet-deployer
import { thanisandraMainRdIsochronePoints } from "./polygonSpreadsheetThanisandra";
import { hebbalCorridorIsochronePoints } from "./polygonSpreadsheetHebbal";
import { devanahalliPlottedArcIsochronePoints } from "./polygonSpreadsheetDevanahalli";

// the-bhoomi-to-bengaluru-journal
import { bellandurPanathurIsochronePoints } from "./polygonBhoomiBellandur";
import { devanahalliAirportCorridorIsochronePoints } from "./polygonBhoomiDevanahalli";
import { sarjapurRoadIsochronePoints } from "./polygonBhoomiSarjapur";

// the-twelve-keys-journal
import { outerRingRoadBellandurIsochronePoints } from "./polygonTwelveKeysOrr";
import { embassyTechvillagePanathurIsochronePoints } from "./polygonTwelveKeysPanathur";
import { manyataTechParkCorridorIsochronePoints } from "./polygonTwelveKeysManyata";

// the-first-emi-family
import { outerSarjapurRoadIsochronePoints } from "./polygonEmiSarjapur";
import { hosaRoadIsochronePoints } from "./polygonEmiHosa";
import { chandapuraAttibeleFringeIsochronePoints } from "./polygonEmiChandapura";

export const POLYGON_POINTS: Record<string, Array<[number, number]>> = {
  // the-3000-miles-home-journal
  whitefield: whitefieldIsochronePoints,
  hennurRoad: hennurRoadIsochronePoints,
  hebbalAirportBelt: hebbalAirportBeltIsochronePoints,

  // the-quiet-crorepatis
  jpNagar7thPhase: jpNagar7thPhaseIsochronePoints,
  jayanagar4thBlock: jayanagar4thBlockIsochronePoints,
  banashankari3rdStage: banashankari3rdStageIsochronePoints,

  // the-spreadsheet-deployer
  thanisandraMainRd: thanisandraMainRdIsochronePoints,
  hebbalCorridor: hebbalCorridorIsochronePoints,
  devanahalliPlottedArc: devanahalliPlottedArcIsochronePoints,

  // the-bhoomi-to-bengaluru-journal
  bellandurPanathur: bellandurPanathurIsochronePoints,
  devanahalliAirportCorridor: devanahalliAirportCorridorIsochronePoints,
  sarjapurRoad: sarjapurRoadIsochronePoints,

  // the-twelve-keys-journal
  outerRingRoadBellandur: outerRingRoadBellandurIsochronePoints,
  embassyTechvillagePanathur: embassyTechvillagePanathurIsochronePoints,
  manyataTechParkCorridor: manyataTechParkCorridorIsochronePoints,

  // the-first-emi-family
  outerSarjapurRoad: outerSarjapurRoadIsochronePoints,
  hosaRoad: hosaRoadIsochronePoints,
  chandapuraAttibeleFringe: chandapuraAttibeleFringeIsochronePoints,
};

/** Resolve a journal's `polygonKey` to its boundary vertices, or undefined. */
export function getPolygonPoints(
  key?: string | null
): Array<[number, number]> | undefined {
  if (!key) return undefined;
  return POLYGON_POINTS[key];
}
